### ISSUE TITLE
Display doesn't update

### ISSUE THREAD

**Issue by 1beb** [konkor/cpufreq#61]
Thanks for this excellent app. Gives me an extra 4 hours of battery on my machine. The extension is working as expected however, the display does not seem to update on the latest version. 

For example, it always shows that all 8 cores on my machine are active even after I have selected for example only 4. Similarly, when I click to turn off turbo, the menu closes. 

Regardless of what's being presented, I can still see that it's working because the display shows the processor frequency (and also if it wasn't my battery would be dead in 5 hours instead of 9). 

I'm not sure how to debug but I can provide you with whatever output you require. 

Ubuntu 17.10 (4.15)
Dell XPS 9560

**Comment by konkor** [comment]
@1beb to see what's going on you have to start from system journal messages in a terminal window. 
This command''ll show all system messages in the monitor mode.
```
sudo journalctl -f
```
Open the monitor, try to change kernel options in the extension. Watch the system messages.

Ubuntu 17.10 has kernel 4.15? - maybe here is a issue in the custom kernel?!
Did you finish installation inside the extension menu (see http://konkor.github.io/cpufreq/install/#finishing-the-installation)?
Did you have removed irqbalance package?

You can try to off cores manually, and see output
```
cpufreqctl off CORENUMBER (1-7 for 8 cores cpu, cpu0 is always on)
```

**Comment by konkor** [comment]
@1beb maybe you have assigned a 'wrong' profile on charging or discharging events and the extension restoring some profile every time?
![](https://github.com/konkor/cpufreq/blob/master/docs/assets/images/posts/power_events.png?raw=true)

**Comment by konkor** [comment]
Just tested on Ubuntu 18.04 Kernel 4.15 (acpi_cpfufreq) works fine.
_oh this color emojis... lol_
![screenshot from 2018-03-08 08-42-53](https://user-images.githubusercontent.com/1944781/37143190-067f6342-22c3-11e8-9ef7-97d63401b90a.png)

**Comment by orowashere** [comment]
I see a lot of messages like this: 

```
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #7 0x7ffc9c12fc50 I   resource:///org/gnome/gjs/modules/signals.js:126 (0x7fb1d66cff78 @ 386)
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #8 0x7ffc9c12fd00 b   resource:///org/gnome/shell/ui/tweener.js:207 (0x7fb1d66cf5e8 @ 159)
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #9 0x7ffc9c12fd70 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb1d66b4de0 @ 71)
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #10 0x7ffc9c12fd70 I   resource:///org/gnome/shell/ui/tweener.js:182 (0x7fb1d66cf560 @ 15)
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: == Stack trace for context 0x56245986d040 ==
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #0 0x7ffc9c12e900 b   resource:///org/gnome/shell/ui/tweener.js:80 (0x7fb1d66c7cd0 @ 82)
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #1 0x7ffc9c12e9a0 b   resource:///org/gnome/shell/ui/tweener.js:105 (0x7fb1d66c7f78 @ 36)
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #2 0x7ffc9c12ea40 b   resource:///org/gnome/shell/ui/tweener.js:92 (0x7fb1d66c7de0 @ 52)
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #3 0x7ffc9c12f940 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:203 (0x7fb1d66d2918 @ 54)
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #4 0x7ffc9c12fa90 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:332 (0x7fb1d66d29a0 @ 1626)
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #5 0x7ffc9c12fb40 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:345 (0x7fb1d66d2a28 @ 100)
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #6 0x7ffc9c12fbd0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:360 (0x7fb1d66d2ab0 @ 10)
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #7 0x7ffc9c12fc50 I   resource:///org/gnome/gjs/modules/signals.js:126 (0x7fb1d66cff78 @ 386)
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #8 0x7ffc9c12fd00 b   resource:///org/gnome/shell/ui/tweener.js:207 (0x7fb1d66cf5e8 @ 159)
Mar 19 12:27:01 42 gnome-shell[11560]: Object Shell.GenericContainer (0x562461354ca0), has been already finalized. Impossible to set any property to it.
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #9 0x7ffc9c12fd70 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb1d66b4de0 @ 71)
Mar 19 12:27:01 42 org.gnome.Shell.desktop[11560]: #10 0x7ffc9c12fd70 I   resource:///org/gnome/shell/ui/tweener.js:182 (0x7fb1d66cf560 @ 15)
Mar 19 12:27:04 42 kernel: Bluetooth: hci0: last event is not cmd complete (0x0f)
Mar 19 12:27:20 42 kernel: Bluetooth: hci0: last event is not cmd complete (0x0f)
Mar 19 12:27:36 42 kernel: Bluetooth: hci0: last event is not cmd complete (0x0f)
Mar 19 12:27:43 42 org.gnome.Shell.desktop[11560]: pkexec must be setuid root
Mar 19 12:27:52 42 kernel: Bluetooth: hci0: last event is not cmd complete (0x0f)
```

```
Mar 19 12:39:23 42 gnome-shell[11560]: Object Shell.GenericContainer (0x5624625bb8f0), has been already finalized. Impossible to get any property from it.
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: == Stack trace for context 0x56245986d040 ==
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #0 0x562459b69a98 i   resource:///org/gnome/shell/ui/tweener.js:73 (0x7fb1d66c7cd0 @ 9)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #1 0x7ffc9c12e380 b   resource:///org/gnome/shell/ui/tweener.js:105 (0x7fb1d66c7f78 @ 36)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #2 0x562459b69a10 i   resource:///org/gnome/shell/ui/tweener.js:92 (0x7fb1d66c7de0 @ 52)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #3 0x7ffc9c12f840 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:203 (0x7fb1d66d2918 @ 54)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #4 0x7ffc9c12f990 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:332 (0x7fb1d66d29a0 @ 1626)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #5 0x7ffc9c12fa40 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:345 (0x7fb1d66d2a28 @ 100)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #6 0x7ffc9c12fad0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:360 (0x7fb1d66d2ab0 @ 10)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #7 0x7ffc9c12fb50 I   resource:///org/gnome/gjs/modules/signals.js:126 (0x7fb1d66cff78 @ 386)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #8 0x7ffc9c12fc00 b   resource:///org/gnome/shell/ui/tweener.js:207 (0x7fb1d66cf5e8 @ 159)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #9 0x7ffc9c12fc60 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb1d66b4de0 @ 71)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #10 0x7ffc9c12fd00 b   resource:///org/gnome/shell/ui/tweener.js:182 (0x7fb1d66cf560 @ 15)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: == Stack trace for context 0x56245986d040 ==
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #0 0x562459b69a98 i   resource:///org/gnome/shell/ui/tweener.js:80 (0x7fb1d66c7cd0 @ 82)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #1 0x7ffc9c12e380 b   resource:///org/gnome/shell/ui/tweener.js:105 (0x7fb1d66c7f78 @ 36)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #2 0x562459b69a10 i   resource:///org/gnome/shell/ui/tweener.js:92 (0x7fb1d66c7de0 @ 52)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #3 0x7ffc9c12f840 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:203 (0x7fb1d66d2918 @ 54)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #4 0x7ffc9c12f990 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:332 (0x7fb1d66d29a0 @ 1626)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #5 0x7ffc9c12fa40 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:345 (0x7fb1d66d2a28 @ 100)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #6 0x7ffc9c12fad0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:360 (0x7fb1d66d2ab0 @ 10)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #7 0x7ffc9c12fb50 I   resource:///org/gnome/gjs/modules/signals.js:126 (0x7fb1d66cff78 @ 386)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #8 0x7ffc9c12fc00 b   resource:///org/gnome/shell/ui/tweener.js:207 (0x7fb1d66cf5e8 @ 159)
Mar 19 12:39:23 42 gnome-shell[11560]: Object Shell.GenericContainer (0x5624625bb8f0), has been already finalized. Impossible to set any property to it.
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #9 0x7ffc9c12fc60 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fb1d66b4de0 @ 71)
Mar 19 12:39:23 42 org.gnome.Shell.desktop[11560]: #10 0x7ffc9c12fd00 b   resource:///org/gnome/shell/ui/tweener.js:182 (0x7fb1d66cf560 @ 15)
```

I'm not sure that any of those are related to the problem.

To answer some of your questions: 

1. Is irqbalance installed, no
2. Did you do the finishing step, no, however, it did not resolve the problem
3. using cpufreqctl is able to turn on and off cores with
4. I checked the extension settings and in both cases (charging / discharging) I have it set to "do nothing" so I'm assuming that shouldn't be a factor

**Comment by terencode** [comment]
@orowashere Those messages are not related, they are due to gjs which added new debug log. They are coming from gnome-shell and are being fixed with https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/4 .

**Comment by konkor** [comment]
@1beb 1. You have to give permissions to the extension to able to change the Kernel settings (It's not optional. Otherwise you'll be able to monitor only or even nothing). http://konkor.github.io/cpufreq/install/#finishing-the-installation
2. After running sudo journalctl -f in a monitor mode, you have to try to change some settings in the extension menu to see some related messages.

**Comment by 1beb** [comment]
That's the thing. I did give it permissions by running that command and it
did not resolve the problem.

**Comment by konkor** [comment]
@1beb I'm closing the issue. It was GJS bug on some versions and it's already fixed and inside i have workaround for it too.
